### PR TITLE
fix: fix readme test

### PR DESCRIPTION
**Pull request by samsja**
# Context

will fix broken ci and test coverage on main

### CODE REVIEW

**Comment by JohannesMessner** [comment]
Not sure to understand how this fixes it

**Comment by samsja** [comment]
> Not sure to understand how this fixes it

basically the test is falling bc we try to run the jina part of the readme without installing jina. I just added jina to the ignore argument like we do with fastapi and all. So it should fix it (hopefully)

**Comment by JohannesMessner** [comment]
I see, that makes sense.
But the readme alone can't crash our coverage from ~80% to ~30%, right?

**Review by JohannesMessner — APPROVED** [review]

**Comment by samsja** [comment]
> I see, that makes sense. But the readme alone can't crash our coverage from ~80% to ~30%, right?

I have no clue honestly

**Review by jupyterjazz — APPROVED** [review]

**Pull request merged**
