### PR TITLE
feat: add validate function to documents to have less verbose api

### PR DESCRIPTION
**Pull request by samsja**
Signed-off-by: samsja <sami.jaghouar@hotmail.fr>
# Comtext

Follow up on this : https://github.com/orgs/docarray/projects/4?pane=issue&itemId=18966242

```python
    class MyDoc(BaseDocument):
        text1: Text
        text2: Text

    MyDoc(text1='hello', text2=Text(text='world'))
```

allow to pass directly a Text

### CODE REVIEW

**Review by JohannesMessner — CHANGES_REQUESTED** [review]
Like it, but I think we should do the same for all of our default docs: identify the main content field and allow that to be passed directly. I think for most of the other ones that would be a tensor instead of `str`

**Comment by samsja** [comment]
yes I will add the resti n this pr as well 

for the other document what do we do 

if it is a string we pass to url ?
if it is a tensor we pass to tensor field ?

@anna-charlotte what do u think ?

**Comment by JohannesMessner** [comment]
> yes I will add the resti n this pr as well
> 
> for the other document what do we do
> 
> if it is a string we pass to url ? if it is a tensor we pass to tensor field ?
> 
> @anna-charlotte what do u think ?

So instead of identifying one main content field per predefined doc we decide based on the input data's type? Could also make sense, but lead to confusion if multiple fields have the same type. E.g. some Document might have two fields of type `str`, then we need to choose one of those

**Comment by samsja** [comment]
> So instead of identifying one main content field per predefined doc we decide based on the input data's type? Could also make sense, but lead to confusion if multiple fields have the same type. E.g. some Document might have two fields of type `str`, then we need to choose one of those

but we do this only for the one that make sense. But nothing automatic

**Review by JoanFM — APPROVED** [review]

**Review by JoanFM — APPROVED** [review]

**Comment by samsja** [comment]
> For the `Audio` doc we could do the same, right? @samsja

I forgot this one

**Comment by samsja** [comment]
partially fix : https://github.com/docarray/docarray/issues/1056

**Pull request merged**
