### PR TITLE
refactor: optimization on stacking

### PR DESCRIPTION
**Pull request by samsja**
# Context

We recently introduced some refactoring on DocumentArrayStacked : https://github.com/docarray/docarray/pull/1008 which change a little bit the way we handled the stacking (We removed any state where the document does not hold the data but instead some time its hold a view of the data that has been moved to the column)

As noticed by @JohannesMessner this new way of stacking could be optimized because once the data has been stacked we re traverse the DocumentArray to put the view from the column to the document.

_Originally posted by @samsja in https://github.com/docarray/docarray/pull/1008#discussion_r1067114135_ there is room for improvements. 
We could:
* pre-allocate the data for the tensor column (we can predict the shape and the type by looking at the first row of the da)
* when collecting the actual data we could replace the data with a view to the pre alocated column 
* when stacking put the data into the preallocate column in place. Therefore each document has already a view to the good part of the column and we don't need iterate again

# What this PR do:

* Use the optimization explained above
* refactor the column creation code base to make it more concise and more readable

### CODE REVIEW

**Comment by samsja** [comment]
> LGTM, but did we make sure that this is equivalent to `torch.stack()` with no unintended consequnces?

I am not sure to understand the question. What "this" refer to here ?

**Comment by JohannesMessner** [comment]
> > LGTM, but did we make sure that this is equivalent to `torch.stack()` with no unintended consequnces?
> 
> I am not sure to understand the question. What "this" refer to here ?

We talked about this on the other PR; "this" being the technique where we pre-allocate a tensor of desired shape and then set slices of it iteratively. I just want to make sure that that doesn't do anything funky in terms of runtime/memory that `torch.stack()` wouldn't do

**Comment by samsja** [comment]
> > LGTM, but did we make sure that this is equivalent to `torch.stack()` with no unintended consequnces?
>
> I am not sure to understand the question. What "this" refer to here ?

okay now I remember, unfortunately https://discuss.pytorch.org/t/what-is-happening-under-the-hood-when-calling-torch-stack/170105 nobody responded to me on pytorch forums. Though I checked it looks like it is doing the same, and from my understanding it should do the same

**Comment by JohannesMessner** [comment]
> > > LGTM, but did we make sure that this is equivalent to `torch.stack()` with no unintended consequnces?
> > 
> > 
> > I am not sure to understand the question. What "this" refer to here ?
> 
> okay now I remember, unfortunately https://discuss.pytorch.org/t/what-is-happening-under-the-hood-when-calling-torch-stack/170105 nobody responded to me on pytorch forums. Though I checked it looks like it is doing the same, and from my understanding it should do the same

Okay then!

**Review by JohannesMessner — APPROVED** [review]

**Pull request merged**
