### PR TITLE
docs: add mention and example for type coercion

### PR DESCRIPTION
**Pull request by Tanguyabel**
This PR brings changes to the docs where we mention type coercion for Tensor, with an example.

### CODE REVIEW

**Review by samsja — CHANGES_REQUESTED** [review]
looks good.

Tho readme is not the right section for this. 


IMO the best would be that you put it in a Tensor section here : https://docs.docarray.org/data_types/first_steps/

**Comment by Tanguyabel** [comment]
> looks good.
> 
> Tho readme is not the right section for this.
> 
> IMO the best would be that you put it in a Tensor section here : https://docs.docarray.org/data_types/first_steps/

@samsja I understand what you say. I added the mention there because:
- it is in this openable section "Click for more details", where we already mention that one can specify the shape of a tensor, so I thought it could go well together, as it is kinda related
- in the data type section that you mention, there is no subsection related to a generic tensor, instead we focus on specific modality; however, type coercion applies to any kind of tensor. It also looks a bit too much detailed for the data type intro page imo

Any suggestion?

**Review by makram93 — COMMENTED** [review]
should we also highlight type coercion to AnyTensor in this doc?

**Comment by samsja** [comment]
Then lets move it to the BaseDoc section at the end. I don't think we should overload the readme

**Pull request merged**
