### PR TITLE
replace usage of `issubclass` with `safe_issubclass` in `BaseDocWitho…

### LINKED ISSUE #1903: Python 3.10 TypeError: issubclass() arg 1 must be a class
### Initial Checks

- [X] I have read and followed [the docs](https://docs.docarray.org/) and still think this is a bug

### Description

TypeError for issubclass in python 3.10. Works in python 3.11.

I think it is due to usage of `issubclass` that is missed out in the following.
https://github.com/docarray/docarray/blob/75e0033a361a31280709899e94d6f5e14ff4b8ae/docarray/base_doc/doc.py#L328-L330

Related: #1557 #1584

```
Traceback (most recent call last):
  File "/.../test.py", line 12, in <module>
    item.model_dump()
  File "/.../lib/python3.10/site-packages/docarray/base_doc/doc.py", line 520, in model_dump
    return _model_dump(super())
  File "/.../lib/python3.10/site-packages/docarray/base_doc/doc.py", line 488, in _model_dump
    ) = self._exclude_doclist(exclude=exclude)
  File "/.../lib/python3.10/site-packages/docarray/base_doc/doc.py", line 329, in _exclude_doclist
    if isinstance(type_, type) and issubclass(type_, AnyDocArray):
  File "/.../lib/python3.10/abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class
```

### Example Code

```Python
from __future__ import annotations

from docarray import BaseDoc, __version__


class Document(BaseDoc):
    list_str: list[str]


item = Document(list_str=["a", "b", "c"])
item.model_dump()
```

### Python, DocArray & OS Version

```Text
python: 3.10
docarray: 0.40.0
platform: macOS-14.6.1-x86_64-i386-64bit
```

### Affected Components

- [ ] [Vector Database / Index](https://docs.docarray.org/user_guide/storing/docindex/)
- [X] [Representing](https://docs.docarray.org/user_guide/representing/first_step)
- [ ] [Sending](https://docs.docarray.org/user_guide/sending/first_step/)
- [ ] [storing](https://docs.docarray.org/user_guide/storing/first_step/)
- [ ] [multi modal data type](https://docs.docarray.org/data_types/first_steps/)

### PR DESCRIPTION
**Pull request by yxtay**
- replaces usage of `issubclass` with `safe_issubclass` in `BaseDocWithoutID` and `MilvusDocumentIndex`
- remaining usage of `issubclass` are in `safe_issubclass` function and tests only

Fixes #1903

### CODE REVIEW

**Comment by JoanFM** [comment]
Hey @yxtay, I would need you to sign off the commits for the PR to be merged.

**Comment by yxtay** [comment]
Hi @JoanFM, I have amended and signed the commits. Please let me know if any other action is required.

**Comment by JoanFM** [comment]
I am currently away from device, but I will check the test errors once I am back

**Comment by yxtay** [comment]
It looks like many of the failures are due to usage of `docker-compose`, which has been removed since 2024-04-01.

actions/runner-images#9557

**Comment by JoanFM** [comment]
Thanks for the contribution!

**Pull request merged**
