### PR TITLE
chore: update contributing guideline

### PR DESCRIPTION
**Pull request by samsja**
# Context

add tips on running the test

### CODE REVIEW

**Comment by Jackmin801** [comment]
Actually, my running this on my local M1 gets stuck
```console
tests/integrations/torch/data/test_torch_dataset.py::test_torch_dl_multiprocessing [W ParallelNative.cpp:229] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
[W ParallelNative.cpp:229] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
```

Should we add a mark to skip this?

The test runs perfectly fine if you run just that file btw

**Comment by jupyterjazz** [comment]
> 
> Actually, running all the tests like this on my local M1 gets stuck
> 
> tests/integrations/torch/data/test_torch_dataset.py::test_torch_dl_multiprocessing [W ParallelNative.cpp:229] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
> [W ParallelNative.cpp:229] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
> Should we add a mark to skip this?
> 
> The test runs perfectly fine if you run just that file btw
> 
> 


same issue on my M1

**Comment by samsja** [comment]
> 

I guess we can just mark it slow ?

**Comment by samsja** [comment]
@Jackmin801 @jupyterjazz can you try again ?

**Review by Jackmin801 — APPROVED** [review]

**Pull request merged**
