### PR TITLE
feat: support use device id in embed method

### PR DESCRIPTION
**Pull request by bwanglzu**
This pull request allow user to specify a `device_id` along with their `cuda` device. This give users more flexibility when inferencing with GPU, with no breaking change.

Usage:

```diff
da.embed(
    embed_model='resnet_50_without_fc',
    device='cuda',
+   device_id=2,  # use the cuda device with index 2
    ...,
)
```

This one should also fix a paddle issue: paddle paddle use `gpu:device_id` to select cuda devices, not `cuda`. docs [here](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/device/set_device_en.html#set-device).
The previous version of ONNX seems to be not working, now i'm adopting the code from [ONNX](https://github.com/microsoft/onnxruntime/blob/78a29aebbcbd0c3b6dab734f221e0f3bf1e24c97/onnxruntime/python/session.py#L57)

Need to test:

- [x] cuda on torch
- [x] cuda on tf
- [ ] cuda on paddle
- [x] cuda on onnx

Need to change:

- [x] code
- [ ] documentation

### CODE REVIEW

**Comment by bwanglzu** [comment]
the `test_embed` is very urgly, i need to clean it up

**Review by JoanFM — CHANGES_REQUESTED** [review]
we should think about passing multiple devices perhaps?

**Comment by bwanglzu** [comment]
@JoanFM seems it's not supported by torch, `cuda:1, 2`, multiple device id is [not supported by onnx](https://github.com/microsoft/onnxruntime/blob/78a29aebbcbd0c3b6dab734f221e0f3bf1e24c97/onnxruntime/python/session.py#L259) and paddle (they use distributed launcher to set multiple devices, not the `set_device` api).

**Comment by JoanFM** [comment]
> @JoanFM seems it's only supported by torch, `cuda:1, 2`, multiple device id is [not supported by onnx](https://github.com/microsoft/onnxruntime/blob/78a29aebbcbd0c3b6dab734f221e0f3bf1e24c97/onnxruntime/python/session.py#L259) and paddle (they use distributed launcher to set multiple devices, not the `set_device` api).

this can be left by the user to control then?

**Comment by bwanglzu** [comment]
torch `device_id=2`
786B8803-8467-4461-9CE8-4A76B5B9F103

**Comment by bwanglzu** [comment]
tensorflow: 
> 2022-12-19 09:40:34.230259: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 22288 MB memory:  -> device: 2, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:4b:00.0, compute capability: 8.6

42EA7592-C5B1-4282-A045-DE4E7DC63EAB

**Comment by bwanglzu** [comment]
onnx with cuda provider:

59C8204B-8309-409C-83B9-714106BAE035

**Comment by bwanglzu** [comment]
closed because I'll create a new one with DCO

**Pull request closed without merging**
