### PR TITLE
feat: save and load inmemory index

### PR DESCRIPTION
**Pull request by jupyterjazz**
Closes https://github.com/docarray/docarray/issues/1535

### CODE REVIEW

**Review by JoanFM — CHANGES_REQUESTED** [review]
Please edit documentation

**Review by JoanFM — APPROVED** [review]

**Comment by JoanFM** [comment]
I would like to have this also for hnsw one? or it already behaves like this?

**Comment by jupyterjazz** [comment]
@JoanFM hnsw's already cool, it updates index after each change and can load from existing workdir

**Review by samsja — APPROVED** [review]

**Comment by JoanFM** [comment]
@jupyterjazz should we adapt the LangChain integration?

**Review by JoanFM — CHANGES_REQUESTED** [review]
Should we rename the method? I believe `binary` provides no value here. 

WDYT @samsja @jupyterjazz @JohannesMessner ?

**Comment by jupyterjazz** [comment]
> 

> @jupyterjazz should we adapt the LangChain integration?

langchain doesn't need loading from a binary file

**Review by JoanFM — APPROVED** [review]

**Pull request merged**
