### PR TITLE
docs: fix urls to docs.docarray.org

### PR DESCRIPTION
**Pull request by alexcg1**
WIP. Replacing all occurrences of docarray.jina.ai with docs.docarray.org

Signed-off-by: Alex C-G <alexcg@outlook.com>

Goals:

- ...
- ...
- [ ] check and update documentation, if required. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#documentation-guidelines)

### CODE REVIEW

**Comment by alexcg1** [comment]
Several non-markdown files also contain the old URL. I want to confirm it's safe to change these (should be safe if migration was done comprehensively, but want to be sure)

```
rg docarray.jina.ai
```

```
setup.py
43:        # req usage, please see https://docarray.jina.ai/#install
152:        'Documentation': 'https://docarray.jina.ai',

docs/conf.py
48:html_baseurl = 'https://docarray.jina.ai'
164:ogp_site_url = 'https://docarray.jina.ai/'
165:ogp_image = 'https://docarray.jina.ai/_static/banner.png'

docs/html_extra/robots.txt
2:sitemap: https://docarray.jina.ai/sitemap.xml

tests/unit/array/mixins/test_pushpull.py
194:                        image='https://docarray.jina.ai/_images/apple.png',

scripts/docstrings_lint.sh
39:  echo 'failure. make sure to check the guide for docstrings: https://docarray.jina.ai/chapters/docstring.html'

docarray/array/storage/qdrant/find.py
138:        For more information: https://docarray.jina.ai/advanced/document-store/qdrant/#qdrant

docarray/proto/build-proto.sh
25:      "https://docarray.jina.ai/"

docarray/array/mixins/traverse.py
62:                f'`path`:{path} is invalid, please refer to https://docarray.jina.ai/fundamentals/documentarray/access-elements/#index-by-nested-structure'
147:                    f'`path`:{path} is invalid, please refer to https://docarray.jina.ai/fundamentals/documentarray/access-elements/#index-by-nested-structure'
```

**Review by samsja — APPROVED** [review]

**Comment by alexcg1** [comment]
> Several non-markdown files also contain the old URL. I want to confirm it's safe to change these (should be safe if migration was done comprehensively, but want to be sure)
> 
> ```
> rg docarray.jina.ai
> ```
> 
> ```
> setup.py
> 43:        # req usage, please see https://docarray.jina.ai/#install
> 152:        'Documentation': 'https://docarray.jina.ai',
> 
> docs/conf.py
> 48:html_baseurl = 'https://docarray.jina.ai'
> 164:ogp_site_url = 'https://docarray.jina.ai/'
> 165:ogp_image = 'https://docarray.jina.ai/_static/banner.png'
> 
> docs/html_extra/robots.txt
> 2:sitemap: https://docarray.jina.ai/sitemap.xml
> 
> tests/unit/array/mixins/test_pushpull.py
> 194:                        image='https://docarray.jina.ai/_images/apple.png',
> 
> scripts/docstrings_lint.sh
> 39:  echo 'failure. make sure to check the guide for docstrings: https://docarray.jina.ai/chapters/docstring.html'
> 
> docarray/array/storage/qdrant/find.py
> 138:        For more information: https://docarray.jina.ai/advanced/document-store/qdrant/#qdrant
> 
> docarray/proto/build-proto.sh
> 25:      "https://docarray.jina.ai/"
> 
> docarray/array/mixins/traverse.py
> 62:                f'`path`:{path} is invalid, please refer to https://docarray.jina.ai/fundamentals/documentarray/access-elements/#index-by-nested-structure'
> 147:                    f'`path`:{path} is invalid, please refer to https://docarray.jina.ai/fundamentals/documentarray/access-elements/#index-by-nested-structure'
> ```

@samsja I mean this comment. Am I good to change all of the non-markdown files? I want to be sure nothing will break

**Comment by samsja** [comment]
> I want to be sure nothing will break
@alexcg1 I check every link in the code part as well. It is working

**Comment by alexcg1** [comment]
Cool. Ready for review

**Review by JoanFM — APPROVED** [review]

**Pull request merged**
