### PR TITLE
fix: fix dataframe max recursion depth

### PR DESCRIPTION
**Pull request by JoanFM**

### CODE REVIEW

**Comment by JoanFM** [comment]
@samsja actually my question is why `ID` is a subclass of `BaseDoc`?

**Comment by samsja** [comment]
> @samsja actually my question is why ID is a subclass of BaseDoc?

it is not

**Comment by samsja** [comment]
ID is a predefined type like NdArray, TorchTensor, ImageUrl, etc. Therefore they are not BaseDoc nor PydanticModel. They just define validator for pydantic to make it work

**Comment by JoanFM** [comment]
We wil handle this in #1467

**Pull request closed without merging**
