### PR TITLE
fix: fix search in memory with AnyEmbedding

### PR DESCRIPTION
**Pull request by JoanFM**
Allows to do easy search in Memory when AnyEmbedding is used as with `TextDoc` or `ImageDoc`:

```python
index = InMemoryExactNNIndex[TextDoc]()

docs = DocList[TextDoc](
    [TextDoc(text='hey', embedding=np.random.rand(128)) for _ in range(200)]
)
index.index(docs)
res = index.find_batched(docs[0:10], search_field='embedding', limit=5)
```

### CODE REVIEW

**Review by jupyterjazz — COMMENTED** [review]
why was `AnyEmbedding` failing?

**Comment by JoanFM** [comment]
> why was `AnyEmbedding` failing?

It does not have a computational backend attached, so it cannot stack or do anything on tensors

**Review by samsja — COMMENTED** [review]
I think it would be better to change 

`_extract_embedding` directly to look at the type to the AnyTensor

**Comment by JoanFM** [comment]
> I think it would be better to change
> 
> `_extract_embedding` directly to look at the type to the AnyTensor

and what about the compBackend, is it okey If I return the NumpyBackend for AnyTensor as default?

**Review by samsja — APPROVED** [review]

**Pull request merged**
